x-magentic-core-dev-build: &magentic_core_dev_build
  context: .
  dockerfile: services/core/Dockerfile
  target: dev

services:
  magentic_frontend:
    image: magentic_frontend_dev:latest
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
      target: dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./packages/site/src:/app/src
      - ./packages/site/index.html:/app/index.html
      - ./packages/site/vite.config.ts:/app/vite.config.ts
      - ./packages/site/postcss.config.js:/app/postcss.config.js

  magentic_backend:
    image: magentic_backend_dev:latest
    build: *magentic_core_dev_build
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev:backend"]
    volumes:
      - ./packages/core/src:/app/src
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:${MAGENTIC_ANALYZED_SOURCE_CONTAINER_PATH:-/mnt/analyzed-source}:ro

  magentic_worker:
    image: magentic_backend_dev:latest
    build: *magentic_core_dev_build
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev:worker"]
    volumes:
      - ./packages/core/src:/app/src
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:${MAGENTIC_ANALYZED_SOURCE_CONTAINER_PATH:-/mnt/analyzed-source}:ro
