x-magentic-backend-dev-build: &magentic_backend_dev_build
  context: .
  dockerfile: services/backend/Dockerfile
  target: dev

x-magentic-analyzer-php-dev-build: &magentic_analyzer_php_dev_build
  context: .
  dockerfile: services/analyzer-php/Dockerfile

services:
  magentic_frontend:
    image: magentic_frontend_dev:latest
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
      target: dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./packages/site/src:/app/src
      - ./packages/site/public:/app/public
      - ./README.md:/README.md:ro
      - ./packages/site/index.html:/app/index.html
      - ./packages/site/vite.config.ts:/app/vite.config.ts
      - ./packages/site/postcss.config.js:/app/postcss.config.js

  magentic_backend:
    image: magentic_backend_dev:latest
    build: *magentic_backend_dev_build
    environment:
      NODE_ENV: development
      MAGENTIC_CONFIG_PATH: "/app/data/config.json"
    command: ["npm", "run", "dev:backend"]
    volumes:
      - ./packages/core/src:/app/src
      - ./packages/core/schema:/app/schema:ro
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:/mnt/analyzed-source:ro
      - ${MAGENTIC_CONFIG_HOST_PATH:-./data}:/app/data

  magentic_worker:
    image: magentic_backend_dev:latest
    build: *magentic_backend_dev_build
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev:worker"]
    volumes:
      - ./packages/core/src:/app/src
      - ./packages/core/schema:/app/schema:ro
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:/mnt/analyzed-source:ro

  magentic_mcp:
    image: magentic_mcp_dev:latest
    build:
      context: .
      dockerfile: services/mcp/Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    volumes:
      - ./packages/mcp/src:/app/src
      - ./packages/mcp/resource:/app/resource
      - ./packages/mcp/package.json:/app/package.json
      - ./packages/mcp/tsconfig.json:/app/tsconfig.json

  magentic_watcher:
    image: magentic_watcher_dev:latest
    build:
      context: .
      dockerfile: services/watcher/Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    volumes:
      - ./packages/watcher/src:/app/src
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:/mnt/analyzed-source:ro
      - ${MAGENTIC_CONFIG_HOST_PATH:-./data}:/app/data:ro

  magentic_analyzer_php:
    image: magentic_analyzer_php_dev:latest
    build: *magentic_analyzer_php_dev_build
    command:
      [
        "sh",
        "-c",
        "composer install --no-interaction --no-progress --prefer-dist && frankenphp run --config /etc/caddy/Caddyfile"
      ]
    volumes:
      - ./packages/php-analyzer:/app
      - ${MAGENTIC_ANALYZED_SOURCE_HOST_PATH:-./www/path/to/magento/source-code}:/mnt/analyzed-source:ro
